apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aks-func-app-asbq
  name: aks-func-app-asbq
  namespace: aks-azfunction-asbq
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aks-func-app-asbq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aks-func-app-asbq
    spec:
      containers:
      - env:
        - name: AzureFunctionsJobHost__functions__0
          value: AsbqTriggerExample
        envFrom:
        - secretRef:
            name: aks-func-app-asbq
        image: <acr name>.azurecr.io/aks-func-app-asbq:latest
        imagePullPolicy: Always
        name: aks-func-app-asbq
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        resources: {}
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30