apiVersion: v1
data:
  AzureWebJobsStorage: VXNl****************W
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
  SbNamespaceCS: RW5kcG***************************4WmJFb1pJZGErQVNiTHJLc1
kind: Secret
metadata:
  name: aks-func-app-asbq
  namespace: aks-azfunction-asbq
type: Opaque